MODE_DAILY_CASES = 'daily'
MODE_DAILY_DEATHS = 'deaths'
MODE_STACK = 'stack'
MODE_DAILY_RECOVERED = 'recovered'
WARNING_MESSAGE = 'Query Failed for {country}'

LABELS = ['confirmed', 'recovered', 'deaths']
COLORS = ['#5198d6', '#c98a32', '#d65544']
PRIMARY_HEX = '#375a7f'
PRIMARY_RGB = 'rgba(55,90,127,0.5)'

# Enum with Graph Types
class GRAPH_TYPE:
    SCATTER_TOTAL_CASES = 0
    BAR_DAILY_CONFIRMED = 1
    BAR_DAILY_DEATHS = 2
    BAR_DAILY_RECOVERED = 3
    BAR_DAILY_DEATHS_RECOVERED_STACKED = 4


# Dictionary Constants
CONTINENTS = {'AS': 'asia', 'AF': 'africa', 'NA': 'north america', 'SA': 'south america', 'EU': 'europe', 'AU': 'world',
              'OC': 'world'}

GRAPH_DROPDOWN_OPTIONS = [{'label': 'Total Cases', 'value': GRAPH_TYPE.SCATTER_TOTAL_CASES},
                          {'label': 'Daily Confirmed', 'value': GRAPH_TYPE.BAR_DAILY_CONFIRMED},
                          {'label': 'Daily Recovered', 'value': GRAPH_TYPE.BAR_DAILY_RECOVERED},
                          {'label': 'Daily Deaths', 'value': GRAPH_TYPE.BAR_DAILY_DEATHS},
                          {'label': 'Daily-Deaths Cases (Stacked)',
                           'value': GRAPH_TYPE.BAR_DAILY_DEATHS_RECOVERED_STACKED}]

COUNTRY_DROPDOWN = [{'label': 'ALA Aland Islands', 'value': 'ala-aland-islands'},
                    {'label': 'Afghanistan', 'value': 'afghanistan'}, {'label': 'Albania', 'value': 'albania'},
                    {'label': 'Algeria', 'value': 'algeria'}, {'label': 'American Samoa', 'value': 'american-samoa'},
                    {'label': 'Andorra', 'value': 'andorra'}, {'label': 'Angola', 'value': 'angola'},
                    {'label': 'Anguilla', 'value': 'anguilla'}, {'label': 'Antarctica', 'value': 'antarctica'},
                    {'label': 'Antigua and Barbuda', 'value': 'antigua-and-barbuda'},
                    {'label': 'Argentina', 'value': 'argentina'}, {'label': 'Armenia', 'value': 'armenia'},
                    {'label': 'Aruba', 'value': 'aruba'}, {'label': 'Australia', 'value': 'australia'},
                    {'label': 'Austria', 'value': 'austria'}, {'label': 'Azerbaijan', 'value': 'azerbaijan'},
                    {'label': 'Bahamas', 'value': 'bahamas'}, {'label': 'Bahrain', 'value': 'bahrain'},
                    {'label': 'Bangladesh', 'value': 'bangladesh'}, {'label': 'Barbados', 'value': 'barbados'},
                    {'label': 'Belarus', 'value': 'belarus'}, {'label': 'Belgium', 'value': 'belgium'},
                    {'label': 'Belize', 'value': 'belize'}, {'label': 'Benin', 'value': 'benin'},
                    {'label': 'Bermuda', 'value': 'bermuda'}, {'label': 'Bhutan', 'value': 'bhutan'},
                    {'label': 'Bolivia', 'value': 'bolivia'},
                    {'label': 'Bosnia and Herzegovina', 'value': 'bosnia-and-herzegovina'},
                    {'label': 'Botswana', 'value': 'botswana'}, {'label': 'Bouvet Island', 'value': 'bouvet-island'},
                    {'label': 'Brazil', 'value': 'brazil'},
                    {'label': 'British Indian Ocean Territory', 'value': 'british-indian-ocean-territory'},
                    {'label': 'British Virgin Islands', 'value': 'british-virgin-islands'},
                    {'label': 'Brunei Darussalam', 'value': 'brunei'},
                    {'label': 'Bulgaria', 'value': 'bulgaria'}, {'label': 'Burkina Faso', 'value': 'burkina-faso'},
                    {'label': 'Burundi', 'value': 'burundi'}, {'label': 'Cambodia', 'value': 'cambodia'},
                    {'label': 'Cameroon', 'value': 'cameroon'}, {'label': 'Canada', 'value': 'canada'},
                    {'label': 'Cape Verde', 'value': 'cape-verde'},
                    {'label': 'Cayman Islands', 'value': 'cayman-islands'},
                    {'label': 'Central African Republic', 'value': 'central-african-republic'},
                    {'label': 'Chad', 'value': 'chad'},
                    {'label': 'Chile', 'value': 'chile'}, {'label': 'China', 'value': 'china'},
                    {'label': 'Christmas Island', 'value': 'christmas-island'},
                    {'label': 'Cocos (Keeling) Islands', 'value': 'cocos-keeling-islands'},
                    {'label': 'Colombia', 'value': 'colombia'},
                    {'label': 'Comoros', 'value': 'comoros'},
                    {'label': 'Congo (Brazzaville)', 'value': 'congo-brazzaville'},
                    {'label': 'Congo (Kinshasa)', 'value': 'congo-kinshasa'},
                    {'label': 'Cook Islands', 'value': 'cook-islands'},
                    {'label': 'Costa Rica', 'value': 'costa-rica'}, {'label': 'Croatia', 'value': 'croatia'},
                    {'label': 'Cuba', 'value': 'cuba'}, {'label': 'Cyprus', 'value': 'cyprus'},
                    {'label': 'Czech Republic', 'value': 'czech-republic'},
                    {'label': "Côte d'Ivoire", 'value': 'cote-divoire'},
                    {'label': 'Denmark', 'value': 'denmark'}, {'label': 'Djibouti', 'value': 'djibouti'},
                    {'label': 'Dominica', 'value': 'dominica'},
                    {'label': 'Dominican Republic', 'value': 'dominican-republic'},
                    {'label': 'Ecuador', 'value': 'ecuador'}, {'label': 'Egypt', 'value': 'egypt'},
                    {'label': 'El Salvador', 'value': 'el-salvador'},
                    {'label': 'Equatorial Guinea', 'value': 'equatorial-guinea'},
                    {'label': 'Eritrea', 'value': 'eritrea'}, {'label': 'Estonia', 'value': 'estonia'},
                    {'label': 'Ethiopia', 'value': 'ethiopia'},
                    {'label': 'Falkland Islands (Malvinas)', 'value': 'falkland-islands-malvinas'},
                    {'label': 'Faroe Islands', 'value': 'faroe-islands'},
                    {'label': 'Fiji', 'value': 'fiji'}, {'label': 'Finland', 'value': 'finland'},
                    {'label': 'France', 'value': 'france'},
                    {'label': 'French Guiana', 'value': 'french-guiana'},
                    {'label': 'French Polynesia', 'value': 'french-polynesia'},
                    {'label': 'French Southern Territories', 'value': 'french-southern-territories'},
                    {'label': 'Gabon', 'value': 'gabon'},
                    {'label': 'Gambia', 'value': 'gambia'}, {'label': 'Georgia', 'value': 'georgia'},
                    {'label': 'Germany', 'value': 'germany'},
                    {'label': 'Ghana', 'value': 'ghana'}, {'label': 'Gibraltar', 'value': 'gibraltar'},
                    {'label': 'Greece', 'value': 'greece'},
                    {'label': 'Greenland', 'value': 'greenland'}, {'label': 'Grenada', 'value': 'grenada'},
                    {'label': 'Guadeloupe', 'value': 'guadeloupe'},
                    {'label': 'Guam', 'value': 'guam'}, {'label': 'Guatemala', 'value': 'guatemala'},
                    {'label': 'Guernsey', 'value': 'guernsey'},
                    {'label': 'Guinea', 'value': 'guinea'}, {'label': 'Guinea-Bissau', 'value': 'guinea-bissau'},
                    {'label': 'Guyana', 'value': 'guyana'},
                    {'label': 'Haiti', 'value': 'haiti'},
                    {'label': 'Heard and Mcdonald Islands', 'value': 'heard-and-mcdonald-islands'},
                    {'label': 'Holy See (Vatican City State)', 'value': 'holy-see-vatican-city-state'},
                    {'label': 'Honduras', 'value': 'honduras'},
                    {'label': 'Hong Kong, SAR China', 'value': 'hong-kong-sar-china'},
                    {'label': 'Hungary', 'value': 'hungary'}, {'label': 'Iceland', 'value': 'iceland'},
                    {'label': 'India', 'value': 'india'},
                    {'label': 'Indonesia', 'value': 'indonesia'},
                    {'label': 'Iran, Islamic Republic of', 'value': 'iran'},
                    {'label': 'Iraq', 'value': 'iraq'},
                    {'label': 'Ireland', 'value': 'ireland'}, {'label': 'Isle of Man', 'value': 'isle-of-man'},
                    {'label': 'Israel', 'value': 'israel'},
                    {'label': 'Italy', 'value': 'italy'}, {'label': 'Jamaica', 'value': 'jamaica'},
                    {'label': 'Japan', 'value': 'japan'},
                    {'label': 'Jersey', 'value': 'jersey'}, {'label': 'Jordan', 'value': 'jordan'},
                    {'label': 'Kazakhstan', 'value': 'kazakhstan'},
                    {'label': 'Kenya', 'value': 'kenya'}, {'label': 'Kiribati', 'value': 'kiribati'},
                    {'label': 'Korea (North)', 'value': 'korea-north'},
                    {'label': 'Korea (South)', 'value': 'korea-south'}, {'label': 'Kuwait', 'value': 'kuwait'},
                    {'label': 'Kyrgyzstan', 'value': 'kyrgyzstan'},
                    {'label': 'Lao PDR', 'value': 'lao-pdr'}, {'label': 'Latvia', 'value': 'latvia'},
                    {'label': 'Lebanon', 'value': 'lebanon'},
                    {'label': 'Lesotho', 'value': 'lesotho'}, {'label': 'Liberia', 'value': 'liberia'},
                    {'label': 'Libya', 'value': 'libya'},
                    {'label': 'Liechtenstein', 'value': 'liechtenstein'}, {'label': 'Lithuania', 'value': 'lithuania'},
                    {'label': 'Luxembourg', 'value': 'luxembourg'},
                    {'label': 'Macao, SAR China', 'value': 'macao-sar-china'},
                    {'label': 'Macedonia, Republic of', 'value': 'macedonia'},
                    {'label': 'Madagascar', 'value': 'madagascar'}, {'label': 'Malawi', 'value': 'malawi'},
                    {'label': 'Malaysia', 'value': 'malaysia'},
                    {'label': 'Maldives', 'value': 'maldives'}, {'label': 'Mali', 'value': 'mali'},
                    {'label': 'Malta', 'value': 'malta'},
                    {'label': 'Marshall Islands', 'value': 'marshall-islands'},
                    {'label': 'Martinique', 'value': 'martinique'},
                    {'label': 'Mauritania', 'value': 'mauritania'}, {'label': 'Mauritius', 'value': 'mauritius'},
                    {'label': 'Mayotte', 'value': 'mayotte'},
                    {'label': 'Mexico', 'value': 'mexico'},
                    {'label': 'Micronesia, Federated States of', 'value': 'micronesia'},
                    {'label': 'Moldova', 'value': 'moldova'}, {'label': 'Monaco', 'value': 'monaco'},
                    {'label': 'Mongolia', 'value': 'mongolia'},
                    {'label': 'Montenegro', 'value': 'montenegro'}, {'label': 'Montserrat', 'value': 'montserrat'},
                    {'label': 'Morocco', 'value': 'morocco'},
                    {'label': 'Mozambique', 'value': 'mozambique'}, {'label': 'Myanmar', 'value': 'myanmar'},
                    {'label': 'Namibia', 'value': 'namibia'},
                    {'label': 'Nauru', 'value': 'nauru'}, {'label': 'Nepal', 'value': 'nepal'},
                    {'label': 'Netherlands', 'value': 'netherlands'},
                    {'label': 'Netherlands Antilles', 'value': 'netherlands-antilles'},
                    {'label': 'New Caledonia', 'value': 'new-caledonia'},
                    {'label': 'New Zealand', 'value': 'new-zealand'}, {'label': 'Nicaragua', 'value': 'nicaragua'},
                    {'label': 'Niger', 'value': 'niger'},
                    {'label': 'Nigeria', 'value': 'nigeria'}, {'label': 'Niue', 'value': 'niue'},
                    {'label': 'Norfolk Island', 'value': 'norfolk-island'},
                    {'label': 'Northern Mariana Islands', 'value': 'northern-mariana-islands'},
                    {'label': 'Norway', 'value': 'norway'},
                    {'label': 'Oman', 'value': 'oman'}, {'label': 'Pakistan', 'value': 'pakistan'},
                    {'label': 'Palau', 'value': 'palau'},
                    {'label': 'Palestinian Territory', 'value': 'palestine'}, {'label': 'Panama', 'value': 'panama'},
                    {'label': 'Papua New Guinea', 'value': 'papua-new-guinea'},
                    {'label': 'Paraguay', 'value': 'paraguay'},
                    {'label': 'Peru', 'value': 'peru'}, {'label': 'Philippines', 'value': 'philippines'},
                    {'label': 'Pitcairn', 'value': 'pitcairn'},
                    {'label': 'Poland', 'value': 'poland'}, {'label': 'Portugal', 'value': 'portugal'},
                    {'label': 'Puerto Rico', 'value': 'puerto-rico'},
                    {'label': 'Qatar', 'value': 'qatar'}, {'label': 'Republic of Kosovo', 'value': 'kosovo'},
                    {'label': 'Romania', 'value': 'romania'},
                    {'label': 'Russian Federation', 'value': 'russia'}, {'label': 'Rwanda', 'value': 'rwanda'},
                    {'label': 'Réunion', 'value': 'réunion'},
                    {'label': 'Saint Helena', 'value': 'saint-helena'},
                    {'label': 'Saint Kitts and Nevis', 'value': 'saint-kitts-and-nevis'},
                    {'label': 'Saint Lucia', 'value': 'saint-lucia'},
                    {'label': 'Saint Pierre and Miquelon', 'value': 'saint-pierre-and-miquelon'},
                    {'label': 'Saint Vincent and Grenadines', 'value': 'saint-vincent-and-the-grenadines'},
                    {'label': 'Saint-Barthélemy', 'value': 'saint-barthélemy'},
                    {'label': 'Saint-Martin (French part)', 'value': 'saint-martin-french-part'},
                    {'label': 'Samoa', 'value': 'samoa'},
                    {'label': 'San Marino', 'value': 'san-marino'},
                    {'label': 'Sao Tome and Principe', 'value': 'sao-tome-and-principe'},
                    {'label': 'Saudi Arabia', 'value': 'saudi-arabia'}, {'label': 'Senegal', 'value': 'senegal'},
                    {'label': 'Serbia', 'value': 'serbia'},
                    {'label': 'Seychelles', 'value': 'seychelles'}, {'label': 'Sierra Leone', 'value': 'sierra-leone'},
                    {'label': 'Singapore', 'value': 'singapore'},
                    {'label': 'Slovakia', 'value': 'slovakia'}, {'label': 'Slovenia', 'value': 'slovenia'},
                    {'label': 'Solomon Islands', 'value': 'solomon-islands'},
                    {'label': 'Somalia', 'value': 'somalia'}, {'label': 'South Africa', 'value': 'south-africa'},
                    {'label': 'South Georgia and the South Sandwich Islands',
                     'value': 'south-georgia-and-the-south-sandwich-islands'},
                    {'label': 'South Sudan', 'value': 'south-sudan'}, {'label': 'Spain', 'value': 'spain'},
                    {'label': 'Sri Lanka', 'value': 'sri-lanka'},
                    {'label': 'Sudan', 'value': 'sudan'}, {'label': 'Suriname', 'value': 'suriname'},
                    {'label': 'Svalbard and Jan Mayen Islands', 'value': 'svalbard-and-jan-mayen-islands'},
                    {'label': 'Swaziland', 'value': 'swaziland'}, {'label': 'Sweden', 'value': 'sweden'},
                    {'label': 'Switzerland', 'value': 'switzerland'},
                    {'label': 'Syrian Arab Republic (Syria)', 'value': 'syria'},
                    {'label': 'Taiwan, Republic of China', 'value': 'taiwan'},
                    {'label': 'Tajikistan', 'value': 'tajikistan'},
                    {'label': 'Tanzania, United Republic of', 'value': 'tanzania'},
                    {'label': 'Thailand', 'value': 'thailand'}, {'label': 'Timor-Leste', 'value': 'timor-leste'},
                    {'label': 'Togo', 'value': 'togo'},
                    {'label': 'Tokelau', 'value': 'tokelau'}, {'label': 'Tonga', 'value': 'tonga'},
                    {'label': 'Trinidad and Tobago', 'value': 'trinidad-and-tobago'},
                    {'label': 'Tunisia', 'value': 'tunisia'}, {'label': 'Turkey', 'value': 'turkey'},
                    {'label': 'Turkmenistan', 'value': 'turkmenistan'},
                    {'label': 'Turks and Caicos Islands', 'value': 'turks-and-caicos-islands'},
                    {'label': 'Tuvalu', 'value': 'tuvalu'},
                    {'label': 'US Minor Outlying Islands', 'value': 'us-minor-outlying-islands'},
                    {'label': 'Uganda', 'value': 'uganda'},
                    {'label': 'Ukraine', 'value': 'ukraine'},
                    {'label': 'United Arab Emirates', 'value': 'united-arab-emirates'},
                    {'label': 'United Kingdom', 'value': 'united-kingdom'},
                    {'label': 'United States of America', 'value': 'united-states'},
                    {'label': 'Uruguay', 'value': 'uruguay'}, {'label': 'Uzbekistan', 'value': 'uzbekistan'},
                    {'label': 'Vanuatu', 'value': 'vanuatu'},
                    {'label': 'Venezuela (Bolivarian Republic)', 'value': 'venezuela'},
                    {'label': 'Viet Nam', 'value': 'vietnam'},
                    {'label': 'Virgin Islands, US', 'value': 'virgin-islands'},
                    {'label': 'Wallis and Futuna Islands', 'value': 'wallis-and-futuna-islands'},
                    {'label': 'Western Sahara', 'value': 'western-sahara'}, {'label': 'Yemen', 'value': 'yemen'},
                    {'label': 'Zambia', 'value': 'zambia'},
                    {'label': 'Zimbabwe', 'value': 'zimbabwe'}]

# Convert slug to ISO2
COUNTRY_ISO2 = {'botswana': 'BW', 'paraguay': 'PY', 'russia': 'RU',
                'turkmenistan': 'TM', 'cambodia': 'KH', 'guinea-bissau': 'GW',
                'new-caledonia': 'NC', 'senegal': 'SN', 'hungary': 'HU',
                'morocco': 'MA', 'syria': 'SY', 'belgium': 'BE',
                'costa-rica': 'CR', 'faroe-islands': 'FO', 'french-guiana': 'GF',
                'mayotte': 'YT', 'new-zealand': 'NZ', 'solomon-islands': 'SB',
                'bouvet-island': 'BV', 'hong-kong-sar-china': 'HK',
                'united-kingdom': 'GB', 'dominica': 'DM', 'malawi': 'MW',
                'mongolia': 'MN', 'guernsey': 'GG', 'saudi-arabia': 'SA',
                'bangladesh': 'BD', 'montenegro': 'ME', 'nigeria': 'NG',
                'niue': 'NU', 'ukraine': 'UA', 'benin': 'BJ', 'cuba': 'CU',
                'ecuador': 'EC', 'israel': 'IL', 'italy': 'IT', 'japan': 'JP',
                'indonesia': 'ID', 'poland': 'PL', 'kosovo': 'XK', 'bahrain': 'BH',
                'cape-verde': 'CV', 'estonia': 'EE', 'guatemala': 'GT',
                'jordan': 'JO', 'nicaragua': 'NI', 'monaco': 'MC',
                'thailand': 'TH', 'turkey': 'TR', 'greece': 'GR',
                'heard-and-mcdonald-islands': 'HM', 'macedonia': 'MK',
                'micronesia': 'FM', 'netherlands': 'NL', 'slovenia': 'SI',
                'zimbabwe': 'ZW', 'anguilla': 'AI', 'georgia': 'GE', 'lao-pdr': 'LA',
                'liberia': 'LR', 'mexico': 'MX', 'tuvalu': 'TV', 'bulgaria': 'BG',
                'fiji': 'FJ', 'palestine': 'PS', 'taiwan': 'TW', 'albania': 'AL',
                'palau': 'PW', 'guam': 'GU', 'guinea': 'GN', 'afghanistan': 'AF',
                'haiti': 'HT', 'samoa': 'WS', 'sri-lanka': 'LK',
                'british-indian-ocean-territory': 'IO', 'congo-brazzaville': 'CG',
                'lebanon': 'LB', 'uruguay': 'UY', 'northern-mariana-islands': 'MP',
                'norway': 'NO', 'saint-helena': 'SH', 'cameroon': 'CM',
                'cook-islands': 'CK', 'marshall-islands': 'MH',
                'papua-new-guinea': 'PG', 'romania': 'RO', 'venezuela': 'VE',
                'libya': 'LY', 'netherlands-antilles': 'AN',
                'south-georgia-and-the-south-sandwich-islands': 'GS',
                'us-minor-outlying-islands': 'UM',
                'falkland-islands-malvinas': 'FK', 'malaysia': 'MY',
                'malta': 'MT', 'norfolk-island': 'NF', 'tunisia': 'TN',
                'greenland': 'GL', 'nepal': 'NP', 'switzerland': 'CH',
                'algeria': 'DZ', 'bolivia': 'BO', 'christmas-island': 'CX',
                'grenada': 'GD', 'sweden': 'SE', 'mauritania': 'MR',
                'panama': 'PA', 'saint-lucia': 'LC',
                'central-african-republic': 'CF', 'djibouti': 'DJ', 'gambia': 'GM',
                'réunion': 'RE', 'bosnia-and-herzegovina': 'BA',
                'cote-divoire': 'CI', 'kiribati': 'KI', 'vietnam': 'VN',
                'ireland': 'IE', 'maldives': 'MV', 'pitcairn': 'PN',
                'portugal': 'PT', 'rwanda': 'RW', 'comoros': 'KM',
                'french-polynesia': 'PF', 'iran': 'IR', 'zambia': 'ZM',
                'cayman-islands': 'KY', 'germany': 'DE', 'qatar': 'QA',
                'yemen': 'YE', 'antarctica': 'AQ',
                'holy-see-vatican-city-state': 'VA', 'san-marino': 'SM',
                'timor-leste': 'TL', 'chad': 'TD', 'togo': 'TG',
                'uzbekistan': 'UZ', 'bhutan': 'BT', 'dominican-republic': 'DO',
                'kyrgyzstan': 'KG', 'philippines': 'PH', 'sudan': 'SD',
                'madagascar': 'MG', 'mozambique': 'MZ', 'seychelles': 'SC',
                'spain': 'ES', 'tanzania': 'TZ', 'namibia': 'NA', 'finland': 'FI',
                'tajikistan': 'TJ', 'armenia': 'AM', 'mali': 'ML',
                'saint-martin-french-part': 'MF', 'czech-republic': 'CZ',
                'kuwait': 'KW', 'myanmar': 'MM', 'ala-aland-islands': 'AX',
                'lithuania': 'LT', 'swaziland': 'SZ', 'burundi': 'BI',
                'argentina': 'AR', 'australia': 'AU', 'bermuda': 'BM',
                'brazil': 'BR', 'kazakhstan': 'KZ', 'lesotho': 'LS',
                'austria': 'AT', 'azerbaijan': 'AZ', 'british-virgin-islands': 'VG',
                'cocos-keeling-islands': 'CC', 'liechtenstein': 'LI',
                'saint-pierre-and-miquelon': 'PM', 'american-samoa': 'AS',
                'angola': 'AO', 'brunei': 'BN', 'guadeloupe': 'GP', 'peru': 'PE',
                'slovakia': 'SK', 'iraq': 'IQ', 'virgin-islands': 'VI',
                'france': 'FR', 'iceland': 'IS', 'pakistan': 'PK',
                'south-africa': 'ZA', 'turks-and-caicos-islands': 'TC',
                'egypt': 'EG', 'gibraltar': 'GI', 'moldova': 'MD', 'nauru': 'NR',
                'oman': 'OM', 'serbia': 'RS', 'bahamas': 'BS', 'chile': 'CL',
                'croatia': 'HR', 'saint-vincent-and-the-grenadines': 'VC',
                'svalbard-and-jan-mayen-islands': 'SJ', 'aruba': 'AW',
                'barbados': 'BB', 'colombia': 'CO', 'el-salvador': 'SV',
                'french-southern-territories': 'TF', 'gabon': 'GA',
                'somalia': 'SO', 'belize': 'BZ', 'china': 'CN', 'india': 'IN',
                'montserrat': 'MS', 'sierra-leone': 'SL', 'singapore': 'SG',
                'niger': 'NE', 'saint-barthélemy': 'BL', 'sao-tome-and-principe': 'ST',
                'united-states': 'US', 'andorra': 'AD', 'belarus': 'BY',
                'burkina-faso': 'BF', 'cyprus': 'CY', 'ghana': 'GH',
                'jersey': 'JE', 'kenya': 'KE', 'south-sudan': 'SS',
                'tonga': 'TO', 'wallis-and-futuna-islands': 'WF',
                'western-sahara': 'EH', 'guyana': 'GY', 'luxembourg': 'LU',
                'macao-sar-china': 'MO', 'united-arab-emirates': 'AE', 'honduras': 'HN',
                'jamaica': 'JM', 'korea-north': 'KP', 'latvia': 'LV',
                'puerto-rico': 'PR', 'saint-kitts-and-nevis': 'KN',
                'congo-kinshasa': 'CD', 'denmark': 'DK', 'equatorial-guinea': 'GQ',
                'eritrea': 'ER', 'ethiopia': 'ET', 'mauritius': 'MU',
                'antigua-and-barbuda': 'AG', 'uganda': 'UG', 'canada': 'CA',
                'isle-of-man': 'IM', 'korea-south': 'KR', 'martinique': 'MQ',
                'suriname': 'SR', 'tokelau': 'TK', 'trinidad-and-tobago': 'TT',
                'vanuatu': 'VU'}

ISO2_TO_CONTINENT = {"BD": "AS", "BE": "EU", "BF": "AF", "BG": "EU", "BA": "EU", "BB": "NA", "WF": "OC", "BL": "NA",
                     "BM": "NA", "BN": "AS",
                     "BO": "SA", "BH": "AS", "BI": "AF", "BJ": "AF", "BT": "AS", "JM": "NA", "BV": "AN", "BW": "AF",
                     "WS": "OC", "BQ": "NA",
                     "BR": "SA", "BS": "NA", "JE": "EU", "BY": "EU", "BZ": "NA", "RU": "EU", "RW": "AF", "RS": "EU",
                     "TL": "OC", "RE": "AF",
                     "TM": "AS", "TJ": "AS", "RO": "EU", "TK": "OC", "GW": "AF", "GU": "OC", "GT": "NA", "GS": "AN",
                     "GR": "EU", "GQ": "AF",
                     "GP": "NA", "JP": "AS", "GY": "SA", "GG": "EU", "GF": "SA", "GE": "AS", "GD": "NA", "GB": "EU",
                     "GA": "AF", "SV": "NA",
                     "GN": "AF", "GM": "AF", "GL": "NA", "GI": "EU", "GH": "AF", "OM": "AS", "TN": "AF", "JO": "AS",
                     "HR": "EU", "HT": "NA",
                     "HU": "EU", "HK": "AS", "HN": "NA", "HM": "AN", "VE": "SA", "PR": "NA", "PS": "AS", "PW": "OC",
                     "PT": "EU", "SJ": "EU",
                     "PY": "SA", "IQ": "AS", "PA": "NA", "PF": "OC", "PG": "OC", "PE": "SA", "PK": "AS", "PH": "AS",
                     "PN": "OC", "PL": "EU",
                     "PM": "NA", "ZM": "AF", "EH": "AF", "EE": "EU", "EG": "AF", "ZA": "AF", "EC": "SA", "IT": "EU",
                     "VN": "AS", "SB": "OC",
                     "ET": "AF", "SO": "AF", "ZW": "AF", "SA": "AS", "ES": "EU", "ER": "AF", "ME": "EU", "MD": "EU",
                     "MG": "AF", "MF": "NA",
                     "MA": "AF", "MC": "EU", "UZ": "AS", "MM": "AS", "ML": "AF", "MO": "AS", "MN": "AS", "MH": "OC",
                     "MK": "EU", "MU": "AF",
                     "MT": "EU", "MW": "AF", "MV": "AS", "MQ": "NA", "MP": "OC", "MS": "NA", "MR": "AF", "IM": "EU",
                     "UG": "AF", "TZ": "AF",
                     "MY": "AS", "MX": "NA", "IL": "AS", "FR": "EU", "IO": "AS", "SH": "AF", "FI": "EU", "FJ": "OC",
                     "FK": "SA", "FM": "OC",
                     "FO": "EU", "NI": "NA", "NL": "EU", "NO": "EU", "NA": "AF", "VU": "OC", "NC": "OC", "NE": "AF",
                     "NF": "OC", "NG": "AF",
                     "NZ": "OC", "NP": "AS", "NR": "OC", "NU": "OC", "CK": "OC", "XK": "EU", "CI": "AF", "CH": "EU",
                     "CO": "SA", "CN": "AS",
                     "CM": "AF", "CL": "SA", "CC": "AS", "CA": "NA", "CG": "AF", "CF": "AF", "CD": "AF", "CZ": "EU",
                     "CY": "EU", "CX": "AS",
                     "CR": "NA", "CW": "NA", "CV": "AF", "CU": "NA", "SZ": "AF", "SY": "AS", "SX": "NA", "KG": "AS",
                     "KE": "AF", "SS": "AF",
                     "SR": "SA", "KI": "OC", "KH": "AS", "KN": "NA", "KM": "AF", "ST": "AF", "SK": "EU", "KR": "AS",
                     "SI": "EU", "KP": "AS",
                     "KW": "AS", "SN": "AF", "SM": "EU", "SL": "AF", "SC": "AF", "KZ": "AS", "KY": "NA", "SG": "AS",
                     "SE": "EU", "SD": "AF",
                     "DO": "NA", "DM": "NA", "DJ": "AF", "DK": "EU", "VG": "NA", "DE": "EU", "YE": "AS", "DZ": "AF",
                     "US": "NA", "UY": "SA",
                     "YT": "AF", "UM": "OC", "LB": "AS", "LC": "NA", "LA": "AS", "TV": "OC", "TW": "AS", "TT": "NA",
                     "TR": "AS", "LK": "AS",
                     "LI": "EU", "LV": "EU", "TO": "OC", "LT": "EU", "LU": "EU", "LR": "AF", "LS": "AF", "TH": "AS",
                     "TF": "AN", "TG": "AF",
                     "TD": "AF", "TC": "NA", "LY": "AF", "VA": "EU", "VC": "NA", "AE": "AS", "AD": "EU", "AG": "NA",
                     "AF": "AS", "AI": "NA",
                     "VI": "NA", "IS": "EU", "IR": "AS", "AM": "AS", "AL": "EU", "AO": "AF", "AQ": "AN", "AS": "OC",
                     "AR": "SA", "AU": "OC",
                     "AT": "EU", "AW": "NA", "IN": "AS", "AX": "EU", "AZ": "AS", "IE": "EU", "ID": "AS", "UA": "EU",
                     "QA": "AS", "MZ": "AF"}

# Convert country name to a slug
COUNTRYSLUG = [{'label': 'ALA Aland Islands', 'value': 'ala-aland-islands'},
               {'label': 'Afghanistan', 'value': 'afghanistan'}, {'label': 'Albania', 'value': 'albania'},
               {'label': 'Algeria', 'value': 'algeria'}, {'label': 'American Samoa', 'value': 'american-samoa'},
               {'label': 'Andorra', 'value': 'andorra'}, {'label': 'Angola', 'value': 'angola'},
               {'label': 'Anguilla', 'value': 'anguilla'}, {'label': 'Antarctica', 'value': 'antarctica'},
               {'label': 'Antigua and Barbuda', 'value': 'antigua-and-barbuda'},
               {'label': 'Argentina', 'value': 'argentina'}, {'label': 'Armenia', 'value': 'armenia'},
               {'label': 'Aruba', 'value': 'aruba'}, {'label': 'Australia', 'value': 'australia'},
               {'label': 'Austria', 'value': 'austria'}, {'label': 'Azerbaijan', 'value': 'azerbaijan'},
               {'label': 'Bahamas', 'value': 'bahamas'}, {'label': 'Bahrain', 'value': 'bahrain'},
               {'label': 'Bangladesh', 'value': 'bangladesh'}, {'label': 'Barbados', 'value': 'barbados'},
               {'label': 'Belarus', 'value': 'belarus'}, {'label': 'Belgium', 'value': 'belgium'},
               {'label': 'Belize', 'value': 'belize'}, {'label': 'Benin', 'value': 'benin'},
               {'label': 'Bermuda', 'value': 'bermuda'}, {'label': 'Bhutan', 'value': 'bhutan'},
               {'label': 'Bolivia', 'value': 'bolivia'},
               {'label': 'Bosnia and Herzegovina', 'value': 'bosnia-and-herzegovina'},
               {'label': 'Botswana', 'value': 'botswana'}, {'label': 'Bouvet Island', 'value': 'bouvet-island'},
               {'label': 'Brazil', 'value': 'brazil'},
               {'label': 'British Indian Ocean Territory', 'value': 'british-indian-ocean-territory'},
               {'label': 'British Virgin Islands', 'value': 'british-virgin-islands'},
               {'label': 'Brunei Darussalam', 'value': 'brunei'},
               {'label': 'Bulgaria', 'value': 'bulgaria'}, {'label': 'Burkina Faso', 'value': 'burkina-faso'},
               {'label': 'Burundi', 'value': 'burundi'}, {'label': 'Cambodia', 'value': 'cambodia'},
               {'label': 'Cameroon', 'value': 'cameroon'}, {'label': 'Canada', 'value': 'canada'},
               {'label': 'Cape Verde', 'value': 'cape-verde'}, {'label': 'Cayman Islands', 'value': 'cayman-islands'},
               {'label': 'Central African Republic', 'value': 'central-african-republic'},
               {'label': 'Chad', 'value': 'chad'},
               {'label': 'Chile', 'value': 'chile'}, {'label': 'China', 'value': 'china'},
               {'label': 'Christmas Island', 'value': 'christmas-island'},
               {'label': 'Cocos (Keeling) Islands', 'value': 'cocos-keeling-islands'},
               {'label': 'Colombia', 'value': 'colombia'},
               {'label': 'Comoros', 'value': 'comoros'}, {'label': 'Congo (Brazzaville)', 'value': 'congo-brazzaville'},
               {'label': 'Congo (Kinshasa)', 'value': 'congo-kinshasa'},
               {'label': 'Cook Islands', 'value': 'cook-islands'},
               {'label': 'Costa Rica', 'value': 'costa-rica'}, {'label': 'Croatia', 'value': 'croatia'},
               {'label': 'Cuba', 'value': 'cuba'}, {'label': 'Cyprus', 'value': 'cyprus'},
               {'label': 'Czech Republic', 'value': 'czech-republic'},
               {'label': "Côte d'Ivoire", 'value': 'cote-divoire'},
               {'label': 'Denmark', 'value': 'denmark'}, {'label': 'Djibouti', 'value': 'djibouti'},
               {'label': 'Dominica', 'value': 'dominica'},
               {'label': 'Dominican Republic', 'value': 'dominican-republic'},
               {'label': 'Ecuador', 'value': 'ecuador'}, {'label': 'Egypt', 'value': 'egypt'},
               {'label': 'El Salvador', 'value': 'el-salvador'},
               {'label': 'Equatorial Guinea', 'value': 'equatorial-guinea'},
               {'label': 'Eritrea', 'value': 'eritrea'}, {'label': 'Estonia', 'value': 'estonia'},
               {'label': 'Ethiopia', 'value': 'ethiopia'},
               {'label': 'Falkland Islands (Malvinas)', 'value': 'falkland-islands-malvinas'},
               {'label': 'Faroe Islands', 'value': 'faroe-islands'},
               {'label': 'Fiji', 'value': 'fiji'}, {'label': 'Finland', 'value': 'finland'},
               {'label': 'France', 'value': 'france'},
               {'label': 'French Guiana', 'value': 'french-guiana'},
               {'label': 'French Polynesia', 'value': 'french-polynesia'},
               {'label': 'French Southern Territories', 'value': 'french-southern-territories'},
               {'label': 'Gabon', 'value': 'gabon'},
               {'label': 'Gambia', 'value': 'gambia'}, {'label': 'Georgia', 'value': 'georgia'},
               {'label': 'Germany', 'value': 'germany'},
               {'label': 'Ghana', 'value': 'ghana'}, {'label': 'Gibraltar', 'value': 'gibraltar'},
               {'label': 'Greece', 'value': 'greece'},
               {'label': 'Greenland', 'value': 'greenland'}, {'label': 'Grenada', 'value': 'grenada'},
               {'label': 'Guadeloupe', 'value': 'guadeloupe'},
               {'label': 'Guam', 'value': 'guam'}, {'label': 'Guatemala', 'value': 'guatemala'},
               {'label': 'Guernsey', 'value': 'guernsey'},
               {'label': 'Guinea', 'value': 'guinea'}, {'label': 'Guinea-Bissau', 'value': 'guinea-bissau'},
               {'label': 'Guyana', 'value': 'guyana'},
               {'label': 'Haiti', 'value': 'haiti'},
               {'label': 'Heard and Mcdonald Islands', 'value': 'heard-and-mcdonald-islands'},
               {'label': 'Holy See (Vatican City State)', 'value': 'holy-see-vatican-city-state'},
               {'label': 'Honduras', 'value': 'honduras'},
               {'label': 'Hong Kong, SAR China', 'value': 'hong-kong-sar-china'},
               {'label': 'Hungary', 'value': 'hungary'}, {'label': 'Iceland', 'value': 'iceland'},
               {'label': 'India', 'value': 'india'},
               {'label': 'Indonesia', 'value': 'indonesia'}, {'label': 'Iran, Islamic Republic of', 'value': 'iran'},
               {'label': 'Iraq', 'value': 'iraq'},
               {'label': 'Ireland', 'value': 'ireland'}, {'label': 'Isle of Man', 'value': 'isle-of-man'},
               {'label': 'Israel', 'value': 'israel'},
               {'label': 'Italy', 'value': 'italy'}, {'label': 'Jamaica', 'value': 'jamaica'},
               {'label': 'Japan', 'value': 'japan'},
               {'label': 'Jersey', 'value': 'jersey'}, {'label': 'Jordan', 'value': 'jordan'},
               {'label': 'Kazakhstan', 'value': 'kazakhstan'},
               {'label': 'Kenya', 'value': 'kenya'}, {'label': 'Kiribati', 'value': 'kiribati'},
               {'label': 'Korea (North)', 'value': 'korea-north'},
               {'label': 'Korea (South)', 'value': 'korea-south'}, {'label': 'Kuwait', 'value': 'kuwait'},
               {'label': 'Kyrgyzstan', 'value': 'kyrgyzstan'},
               {'label': 'Lao PDR', 'value': 'lao-pdr'}, {'label': 'Latvia', 'value': 'latvia'},
               {'label': 'Lebanon', 'value': 'lebanon'},
               {'label': 'Lesotho', 'value': 'lesotho'}, {'label': 'Liberia', 'value': 'liberia'},
               {'label': 'Libya', 'value': 'libya'},
               {'label': 'Liechtenstein', 'value': 'liechtenstein'}, {'label': 'Lithuania', 'value': 'lithuania'},
               {'label': 'Luxembourg', 'value': 'luxembourg'},
               {'label': 'Macao, SAR China', 'value': 'macao-sar-china'},
               {'label': 'Macedonia, Republic of', 'value': 'macedonia'},
               {'label': 'Madagascar', 'value': 'madagascar'}, {'label': 'Malawi', 'value': 'malawi'},
               {'label': 'Malaysia', 'value': 'malaysia'},
               {'label': 'Maldives', 'value': 'maldives'}, {'label': 'Mali', 'value': 'mali'},
               {'label': 'Malta', 'value': 'malta'},
               {'label': 'Marshall Islands', 'value': 'marshall-islands'},
               {'label': 'Martinique', 'value': 'martinique'},
               {'label': 'Mauritania', 'value': 'mauritania'}, {'label': 'Mauritius', 'value': 'mauritius'},
               {'label': 'Mayotte', 'value': 'mayotte'},
               {'label': 'Mexico', 'value': 'mexico'},
               {'label': 'Micronesia, Federated States of', 'value': 'micronesia'},
               {'label': 'Moldova', 'value': 'moldova'}, {'label': 'Monaco', 'value': 'monaco'},
               {'label': 'Mongolia', 'value': 'mongolia'},
               {'label': 'Montenegro', 'value': 'montenegro'}, {'label': 'Montserrat', 'value': 'montserrat'},
               {'label': 'Morocco', 'value': 'morocco'},
               {'label': 'Mozambique', 'value': 'mozambique'}, {'label': 'Myanmar', 'value': 'myanmar'},
               {'label': 'Namibia', 'value': 'namibia'},
               {'label': 'Nauru', 'value': 'nauru'}, {'label': 'Nepal', 'value': 'nepal'},
               {'label': 'Netherlands', 'value': 'netherlands'},
               {'label': 'Netherlands Antilles', 'value': 'netherlands-antilles'},
               {'label': 'New Caledonia', 'value': 'new-caledonia'},
               {'label': 'New Zealand', 'value': 'new-zealand'}, {'label': 'Nicaragua', 'value': 'nicaragua'},
               {'label': 'Niger', 'value': 'niger'},
               {'label': 'Nigeria', 'value': 'nigeria'}, {'label': 'Niue', 'value': 'niue'},
               {'label': 'Norfolk Island', 'value': 'norfolk-island'},
               {'label': 'Northern Mariana Islands', 'value': 'northern-mariana-islands'},
               {'label': 'Norway', 'value': 'norway'},
               {'label': 'Oman', 'value': 'oman'}, {'label': 'Pakistan', 'value': 'pakistan'},
               {'label': 'Palau', 'value': 'palau'},
               {'label': 'Palestinian Territory', 'value': 'palestine'}, {'label': 'Panama', 'value': 'panama'},
               {'label': 'Papua New Guinea', 'value': 'papua-new-guinea'}, {'label': 'Paraguay', 'value': 'paraguay'},
               {'label': 'Peru', 'value': 'peru'}, {'label': 'Philippines', 'value': 'philippines'},
               {'label': 'Pitcairn', 'value': 'pitcairn'},
               {'label': 'Poland', 'value': 'poland'}, {'label': 'Portugal', 'value': 'portugal'},
               {'label': 'Puerto Rico', 'value': 'puerto-rico'},
               {'label': 'Qatar', 'value': 'qatar'}, {'label': 'Republic of Kosovo', 'value': 'kosovo'},
               {'label': 'Romania', 'value': 'romania'},
               {'label': 'Russian Federation', 'value': 'russia'}, {'label': 'Rwanda', 'value': 'rwanda'},
               {'label': 'Réunion', 'value': 'réunion'},
               {'label': 'Saint Helena', 'value': 'saint-helena'},
               {'label': 'Saint Kitts and Nevis', 'value': 'saint-kitts-and-nevis'},
               {'label': 'Saint Lucia', 'value': 'saint-lucia'},
               {'label': 'Saint Pierre and Miquelon', 'value': 'saint-pierre-and-miquelon'},
               {'label': 'Saint Vincent and Grenadines', 'value': 'saint-vincent-and-the-grenadines'},
               {'label': 'Saint-Barthélemy', 'value': 'saint-barthélemy'},
               {'label': 'Saint-Martin (French part)', 'value': 'saint-martin-french-part'},
               {'label': 'Samoa', 'value': 'samoa'},
               {'label': 'San Marino', 'value': 'san-marino'},
               {'label': 'Sao Tome and Principe', 'value': 'sao-tome-and-principe'},
               {'label': 'Saudi Arabia', 'value': 'saudi-arabia'}, {'label': 'Senegal', 'value': 'senegal'},
               {'label': 'Serbia', 'value': 'serbia'},
               {'label': 'Seychelles', 'value': 'seychelles'}, {'label': 'Sierra Leone', 'value': 'sierra-leone'},
               {'label': 'Singapore', 'value': 'singapore'},
               {'label': 'Slovakia', 'value': 'slovakia'}, {'label': 'Slovenia', 'value': 'slovenia'},
               {'label': 'Solomon Islands', 'value': 'solomon-islands'},
               {'label': 'Somalia', 'value': 'somalia'}, {'label': 'South Africa', 'value': 'south-africa'},
               {'label': 'South Georgia and the South Sandwich Islands',
                'value': 'south-georgia-and-the-south-sandwich-islands'},
               {'label': 'South Sudan', 'value': 'south-sudan'}, {'label': 'Spain', 'value': 'spain'},
               {'label': 'Sri Lanka', 'value': 'sri-lanka'},
               {'label': 'Sudan', 'value': 'sudan'}, {'label': 'Suriname', 'value': 'suriname'},
               {'label': 'Svalbard and Jan Mayen Islands', 'value': 'svalbard-and-jan-mayen-islands'},
               {'label': 'Swaziland', 'value': 'swaziland'}, {'label': 'Sweden', 'value': 'sweden'},
               {'label': 'Switzerland', 'value': 'switzerland'},
               {'label': 'Syrian Arab Republic (Syria)', 'value': 'syria'},
               {'label': 'Taiwan, Republic of China', 'value': 'taiwan'},
               {'label': 'Tajikistan', 'value': 'tajikistan'},
               {'label': 'Tanzania, United Republic of', 'value': 'tanzania'},
               {'label': 'Thailand', 'value': 'thailand'}, {'label': 'Timor-Leste', 'value': 'timor-leste'},
               {'label': 'Togo', 'value': 'togo'},
               {'label': 'Tokelau', 'value': 'tokelau'}, {'label': 'Tonga', 'value': 'tonga'},
               {'label': 'Trinidad and Tobago', 'value': 'trinidad-and-tobago'},
               {'label': 'Tunisia', 'value': 'tunisia'}, {'label': 'Turkey', 'value': 'turkey'},
               {'label': 'Turkmenistan', 'value': 'turkmenistan'},
               {'label': 'Turks and Caicos Islands', 'value': 'turks-and-caicos-islands'},
               {'label': 'Tuvalu', 'value': 'tuvalu'},
               {'label': 'US Minor Outlying Islands', 'value': 'us-minor-outlying-islands'},
               {'label': 'Uganda', 'value': 'uganda'},
               {'label': 'Ukraine', 'value': 'ukraine'},
               {'label': 'United Arab Emirates', 'value': 'united-arab-emirates'},
               {'label': 'United Kingdom', 'value': 'united-kingdom'},
               {'label': 'United States of America', 'value': 'united-states'},
               {'label': 'Uruguay', 'value': 'uruguay'}, {'label': 'Uzbekistan', 'value': 'uzbekistan'},
               {'label': 'Vanuatu', 'value': 'vanuatu'},
               {'label': 'Venezuela (Bolivarian Republic)', 'value': 'venezuela'},
               {'label': 'Viet Nam', 'value': 'vietnam'},
               {'label': 'Virgin Islands, US', 'value': 'virgin-islands'},
               {'label': 'Wallis and Futuna Islands', 'value': 'wallis-and-futuna-islands'},
               {'label': 'Western Sahara', 'value': 'western-sahara'}, {'label': 'Yemen', 'value': 'yemen'},
               {'label': 'Zambia', 'value': 'zambia'},
               {'label': 'Zimbabwe', 'value': 'zimbabwe'}]

ISO2_TO_ISO3 = {"BD": "BGD", "BE": "BEL", "BF": "BFA", "BG": "BGR", "BA": "BIH", "BB": "BRB", "WF": "WLF", "BL": "BLM",
                "BM": "BMU", "BN": "BRN", "BO": "BOL", "BH": "BHR", "BI": "BDI", "BJ": "BEN", "BT": "BTN", "JM": "JAM",
                "BV": "BVT", "BW": "BWA", "WS": "WSM", "BQ": "BES", "BR": "BRA", "BS": "BHS", "JE": "JEY", "BY": "BLR",
                "BZ": "BLZ", "RU": "RUS", "RW": "RWA", "RS": "SRB", "TL": "TLS", "RE": "REU", "TM": "TKM", "TJ": "TJK",
                "RO": "ROU", "TK": "TKL", "GW": "GNB", "GU": "GUM", "GT": "GTM", "GS": "SGS", "GR": "GRC", "GQ": "GNQ",
                "GP": "GLP", "JP": "JPN", "GY": "GUY", "GG": "GGY", "GF": "GUF", "GE": "GEO", "GD": "GRD", "GB": "GBR",
                "GA": "GAB", "SV": "SLV", "GN": "GIN", "GM": "GMB", "GL": "GRL", "GI": "GIB", "GH": "GHA", "OM": "OMN",
                "TN": "TUN", "JO": "JOR", "HR": "HRV", "HT": "HTI", "HU": "HUN", "HK": "HKG", "HN": "HND", "HM": "HMD",
                "VE": "VEN", "PR": "PRI", "PS": "PSE", "PW": "PLW", "PT": "PRT", "SJ": "SJM", "PY": "PRY", "IQ": "IRQ",
                "PA": "PAN", "PF": "PYF", "PG": "PNG", "PE": "PER", "PK": "PAK", "PH": "PHL", "PN": "PCN", "PL": "POL",
                "PM": "SPM", "ZM": "ZMB", "EH": "ESH", "EE": "EST", "EG": "EGY", "ZA": "ZAF", "EC": "ECU", "IT": "ITA",
                "VN": "VNM", "SB": "SLB", "ET": "ETH", "SO": "SOM", "ZW": "ZWE", "SA": "SAU", "ES": "ESP", "ER": "ERI",
                "ME": "MNE", "MD": "MDA", "MG": "MDG", "MF": "MAF", "MA": "MAR", "MC": "MCO", "UZ": "UZB", "MM": "MMR",
                "ML": "MLI", "MO": "MAC", "MN": "MNG", "MH": "MHL", "MK": "MKD", "MU": "MUS", "MT": "MLT", "MW": "MWI",
                "MV": "MDV", "MQ": "MTQ", "MP": "MNP", "MS": "MSR", "MR": "MRT", "IM": "IMN", "UG": "UGA", "TZ": "TZA",
                "MY": "MYS", "MX": "MEX", "IL": "ISR", "FR": "FRA", "IO": "IOT", "SH": "SHN", "FI": "FIN", "FJ": "FJI",
                "FK": "FLK", "FM": "FSM", "FO": "FRO", "NI": "NIC", "NL": "NLD", "NO": "NOR", "NA": "NAM", "VU": "VUT",
                "NC": "NCL", "NE": "NER", "NF": "NFK", "NG": "NGA", "NZ": "NZL", "NP": "NPL", "NR": "NRU", "NU": "NIU",
                "CK": "COK", "XK": "XKX", "CI": "CIV", "CH": "CHE", "CO": "COL", "CN": "CHN", "CM": "CMR", "CL": "CHL",
                "CC": "CCK", "CA": "CAN", "CG": "COG", "CF": "CAF", "CD": "COD", "CZ": "CZE", "CY": "CYP", "CX": "CXR",
                "CR": "CRI", "CW": "CUW", "CV": "CPV", "CU": "CUB", "SZ": "SWZ", "SY": "SYR", "SX": "SXM", "KG": "KGZ",
                "KE": "KEN", "SS": "SSD", "SR": "SUR", "KI": "KIR", "KH": "KHM", "KN": "KNA", "KM": "COM", "ST": "STP",
                "SK": "SVK", "KR": "KOR", "SI": "SVN", "KP": "PRK", "KW": "KWT", "SN": "SEN", "SM": "SMR", "SL": "SLE",
                "SC": "SYC", "KZ": "KAZ", "KY": "CYM", "SG": "SGP", "SE": "SWE", "SD": "SDN", "DO": "DOM", "DM": "DMA",
                "DJ": "DJI", "DK": "DNK", "VG": "VGB", "DE": "DEU", "YE": "YEM", "DZ": "DZA", "US": "USA", "UY": "URY",
                "YT": "MYT", "UM": "UMI", "LB": "LBN", "LC": "LCA", "LA": "LAO", "TV": "TUV", "TW": "TWN", "TT": "TTO",
                "TR": "TUR", "LK": "LKA", "LI": "LIE", "LV": "LVA", "TO": "TON", "LT": "LTU", "LU": "LUX", "LR": "LBR",
                "LS": "LSO", "TH": "THA", "TF": "ATF", "TG": "TGO", "TD": "TCD", "TC": "TCA", "LY": "LBY", "VA": "VAT",
                "VC": "VCT", "AE": "ARE", "AD": "AND", "AG": "ATG", "AF": "AFG", "AI": "AIA", "VI": "VIR", "IS": "ISL",
                "IR": "IRN", "AM": "ARM", "AL": "ALB", "AO": "AGO", "AQ": "ATA", "AS": "ASM", "AR": "ARG", "AU": "AUS",
                "AT": "AUT", "AW": "ABW", "IN": "IND", "AX": "ALA", "AZ": "AZE", "IE": "IRL", "ID": "IDN", "UA": "UKR",
                "QA": "QAT", "MZ": "MOZ"}
